### ISSUE TITLE
'request': Moved Permanently (JIRA::HTTPError)

### ISSUE THREAD

**Issue by jjwanat** [sumoheavy/jira-ruby#47]
I've been trying to access JIRA via HTTP basic auth using the example.rb . After running it, I receive that error. I've added the Gist of my script and the received error. Has anyone else run into this? Am I doing anything wrong?

https://gist.github.com/Drekonus/941620bc1129c5167ade

**Comment by endymion** [comment]
OMG this undocumented gem wasted hours of my time tonight because there is no example anywhere for the most common use case.  Fail.  I could have built my project from scratch in less time than it took me to figure this gem out because it's so poorly documented.  I finally figured out: :context_path => ''.  Then I found this.

I spent the last four hours trying to figure out why I get nothing but 400 response with no explanation when I try to update any issue with any update through this gem and I still haven't figured it out.

**Comment by kurtwall** [comment]
Seriously? They don't document the most common use case. :boom:  @jmccartie :trophy:
